import {
  Injectable,
  NotFoundException,
  BadRequestException,
  ConflictException,
  Logger,
} from '@nestjs/common';
import { EventEmitter2, OnEvent } from '@nestjs/event-emitter';
import { Decimal } from '@prisma/client/runtime/library';
import { PrismaService } from '../prisma/prisma.service';
import { StockService } from '../stock/stock.service';
import { CreateOrderDto } from './dto/create-order.dto';
import { CreateGRNDto } from './dto/create-grn.dto';
import { CreateSupplierDto } from './dto/create-supplier.dto';
import { CancelOrderDto } from './dto/cancel-order.dto';
import { OrderQueryDto } from './dto/order-query.dto';
import {
  OrderStatus,
  StockMovementType,
  TransactionCategory,
  PaymentMethod,
} from '@gasstation/shared-types';

const ORDER_INCLUDE = {
  station: { select: { id: true, name: true, city: true } },
  supplier: { select: { id: true, name: true, vatRegNo: true, contactNumber: true } },
  createdBy: { select: { id: true, fullName: true } },
  approvedBy: { select: { id: true, fullName: true } },
  items: true,
  grns: { include: { items: true } },
} as const;

@Injectable()
export class OrdersService {
  private readonly logger = new Logger(OrdersService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly stockService: StockService,
    private readonly events: EventEmitter2,
  ) {}

  // ─── Supplier management ──────────────────────────────────────────────────

  async createSupplier(dto: CreateSupplierDto) {
    return this.prisma.supplier.create({ data: dto });
  }

  async getSuppliers(stationId?: string) {
    if (stationId) {
      const links = await this.prisma.stationSupplier.findMany({
        where: { stationId },
        include: { supplier: true },
        orderBy: [{ isPreferred: 'desc' }],
      });
      return links.map((l) => ({ ...l.supplier, isPreferred: l.isPreferred }));
    }
    return this.prisma.supplier.findMany({
      where: { isActive: true },
      orderBy: { name: 'asc' },
    });
  }

  async linkSupplierToStation(stationId: string, supplierId: string, isPreferred = false) {
    return this.prisma.stationSupplier.upsert({
      where: { stationId_supplierId: { stationId, supplierId } },
      update: { isPreferred },
      create: { stationId, supplierId, isPreferred },
    });
  }

  // ─── Order number generation ──────────────────────────────────────────────

  private async generateOrderNumber(): Promise<string> {
    const year = new Date().getFullYear();
    const count = await this.prisma.purchaseOrder.count({
      where: { orderNumber: { startsWith: `PO-${year}-` } },
    });
    return `PO-${year}-${String(count + 1).padStart(4, '0')}`;
  }

  private async generateGRNNumber(): Promise<string> {
    const year = new Date().getFullYear();
    const count = await this.prisma.goodsReceivedNote.count({
      where: { grnNumber: { startsWith: `GRN-${year}-` } },
    });
    return `GRN-${year}-${String(count + 1).padStart(4, '0')}`;
  }

  // ─── Create purchase order (DRAFT) ────────────────────────────────────────

  async createOrder(dto: CreateOrderDto, userId: string) {
    // Verify station and supplier exist
    const [station, supplier] = await Promise.all([
      this.prisma.station.findUnique({ where: { id: dto.stationId } }),
      this.prisma.supplier.findUnique({ where: { id: dto.supplierId } }),
    ]);
    if (!station) throw new NotFoundException('Station not found');
    if (!supplier) throw new NotFoundException('Supplier not found');

    // Calculate totals per item and grand total
    const itemsWithTotals = dto.items.map((item) => {
      const total = new Decimal(item.quantityLitres).times(item.pricePerLitreLkr);
      return { ...item, totalAmountLkr: total };
    });
    const totalAmountLkr = itemsWithTotals.reduce(
      (sum, i) => sum.plus(i.totalAmountLkr),
      new Decimal(0),
    );

    const orderNumber = await this.generateOrderNumber();

    const order = await this.prisma.purchaseOrder.create({
      data: {
        orderNumber,
        stationId: dto.stationId,
        supplierId: dto.supplierId,
        status: OrderStatus.DRAFT,
        orderDate: new Date(dto.orderDate),
        expectedDeliveryDate: dto.expectedDeliveryDate ? new Date(dto.expectedDeliveryDate) : null,
        totalAmountLkr,
        notes: dto.notes,
        isAutoGenerated: dto.isAutoGenerated ?? false,
        createdById: userId,
        items: {
          create: itemsWithTotals.map((i) => ({
            fuelType: i.fuelType,
            quantityLitres: i.quantityLitres,
            pricePerLitreLkr: i.pricePerLitreLkr,
            totalAmountLkr: i.totalAmountLkr,
          })),
        },
      },
      include: ORDER_INCLUDE,
    });

    await this.auditLog(userId, 'ORDER_CREATED', order.id, orderNumber);
    this.events.emit('order.created', order);

    return this.formatOrder(order);
  }

  // ─── Submit order (DRAFT → SUBMITTED) ─────────────────────────────────────

  async submitOrder(orderId: string, userId: string) {
    const order = await this.getOrderOrThrow(orderId);
    this.assertStatus(order, [OrderStatus.DRAFT], 'submit');

    const updated = await this.prisma.purchaseOrder.update({
      where: { id: orderId },
      data: { status: OrderStatus.SUBMITTED },
      include: ORDER_INCLUDE,
    });

    this.events.emit('order.submitted', updated);
    await this.auditLog(userId, 'ORDER_SUBMITTED', orderId, order.orderNumber);

    return this.formatOrder(updated);
  }

  // ─── Approve order (SUBMITTED → APPROVED) ─────────────────────────────────

  async approveOrder(orderId: string, userId: string) {
    const order = await this.getOrderOrThrow(orderId);
    this.assertStatus(order, [OrderStatus.SUBMITTED], 'approve');

    const updated = await this.prisma.purchaseOrder.update({
      where: { id: orderId },
      data: { status: OrderStatus.APPROVED, approvedById: userId, approvedAt: new Date() },
      include: ORDER_INCLUDE,
    });

    this.events.emit('order.approved', updated);
    await this.auditLog(userId, 'ORDER_APPROVED', orderId, order.orderNumber);

    return this.formatOrder(updated);
  }

  // ─── Cancel order ─────────────────────────────────────────────────────────

  async cancelOrder(orderId: string, userId: string, dto: CancelOrderDto) {
    const order = await this.getOrderOrThrow(orderId);
    if ([OrderStatus.DELIVERED, OrderStatus.CANCELLED].includes(order.status as OrderStatus)) {
      throw new BadRequestException(`Cannot cancel a ${order.status} order`);
    }

    const updated = await this.prisma.purchaseOrder.update({
      where: { id: orderId },
      data: {
        status: OrderStatus.CANCELLED,
        cancellationReason: dto.cancellationReason,
        cancelledAt: new Date(),
      },
      include: ORDER_INCLUDE,
    });

    await this.auditLog(userId, 'ORDER_CANCELLED', orderId, dto.cancellationReason);
    return this.formatOrder(updated);
  }

  // ─── Create GRN (record delivery) ─────────────────────────────────────────

  async createGRN(dto: CreateGRNDto, userId: string) {
    const order = await this.getOrderOrThrow(dto.purchaseOrderId);

    if (![OrderStatus.APPROVED, OrderStatus.PARTIALLY_DELIVERED].includes(order.status as OrderStatus)) {
      throw new BadRequestException(
        `GRN can only be created for APPROVED or PARTIALLY_DELIVERED orders. Current status: ${order.status}`,
      );
    }

    const grnNumber = await this.generateGRNNumber();
    const receivedAt = new Date(dto.receivedAt);

    // Match each GRN item to a tank and build stock movements
    const grnItemData: Array<{
      fuelType: string;
      orderedQtyLitres: number;
      receivedQtyLitres: number;
      pricePerLitreLkr: number;
      totalAmountLkr: Decimal;
      movementId?: string;
    }> = [];

    for (const item of dto.items) {
      // Find the matching tank for this station + fuel type
      const tank = await this.prisma.tank.findUnique({
        where: { stationId_fuelType: { stationId: order.stationId, fuelType: item.fuelType as any } },
      });
      if (!tank) {
        throw new BadRequestException(
          `No tank configured for fuel type ${item.fuelType} at this station`,
        );
      }

      const totalAmount = new Decimal(item.receivedQtyLitres).times(item.pricePerLitreLkr);

      // Create DELIVERY_IN stock movement
      const { movement } = await this.stockService.recordMovement(
        {
          tankId: tank.id,
          type: StockMovementType.DELIVERY_IN,
          quantityLitres: item.receivedQtyLitres,
          unitCostLkr: item.pricePerLitreLkr,
          reference: grnNumber,
          notes: `GRN delivery for PO ${order.orderNumber}`,
        },
        userId,
      );

      grnItemData.push({
        fuelType: item.fuelType,
        orderedQtyLitres: item.orderedQtyLitres,
        receivedQtyLitres: item.receivedQtyLitres,
        pricePerLitreLkr: item.pricePerLitreLkr,
        totalAmountLkr: totalAmount,
        movementId: movement.id,
      });
    }

    const totalReceivedAmount = grnItemData.reduce(
      (s, i) => s.plus(i.totalAmountLkr),
      new Decimal(0),
    );

    // Determine if fully or partially delivered
    const totalOrderedLitres = order.items.reduce(
      (s: number, i: any) => s + Number(i.quantityLitres),
      0,
    );
    const totalReceivedLitres = grnItemData.reduce((s, i) => s + i.receivedQtyLitres, 0);
    const isFullDelivery = totalReceivedLitres >= totalOrderedLitres * 0.98; // 2% tolerance

    // Create GRN + items + update PO atomically
    const [grn] = await this.prisma.$transaction([
      this.prisma.goodsReceivedNote.create({
        data: {
          grnNumber,
          purchaseOrderId: dto.purchaseOrderId,
          receivedAt,
          totalAmountLkr: totalReceivedAmount,
          notes: dto.notes,
          createdById: userId,
          items: {
            create: grnItemData.map((i) => ({
              fuelType: i.fuelType as any,
              orderedQtyLitres: i.orderedQtyLitres,
              receivedQtyLitres: i.receivedQtyLitres,
              pricePerLitreLkr: i.pricePerLitreLkr,
              totalAmountLkr: i.totalAmountLkr,
              stockMovementId: i.movementId,
            })),
          },
        },
        include: { items: true, purchaseOrder: { select: { orderNumber: true } } },
      }),
      this.prisma.purchaseOrder.update({
        where: { id: dto.purchaseOrderId },
        data: {
          status: isFullDelivery ? OrderStatus.DELIVERED : OrderStatus.PARTIALLY_DELIVERED,
          deliveredAt: isFullDelivery ? receivedAt : undefined,
          totalReceivedAmountLkr: totalReceivedAmount,
        },
      }),
    ]);

    // Record FUEL_PURCHASE transaction in the financial ledger
    const fiscalDate = this.getFiscalPeriod(receivedAt);
    await this.prisma.transaction.create({
      data: {
        stationId: order.stationId,
        category: TransactionCategory.FUEL_PURCHASE,
        description: `Fuel purchase — GRN ${grnNumber} / PO ${order.orderNumber}`,
        amountLkr: totalReceivedAmount,
        vatAmountLkr: 0, // input VAT tracked separately via TaxEntry
        netAmountLkr: totalReceivedAmount,
        paymentMethod: PaymentMethod.BANK_TRANSFER,
        transactionDate: receivedAt,
        reference: grnNumber,
        fiscalYear: fiscalDate.year,
        fiscalMonth: fiscalDate.month,
        createdById: userId,
      },
    });

    await this.auditLog(userId, 'GRN_CREATED', grn.id, grnNumber);
    this.events.emit('order.delivered', { grn, orderId: dto.purchaseOrderId });

    return grn;
  }

  // ─── Query orders ─────────────────────────────────────────────────────────

  async getOrders(query: OrderQueryDto, userRole: string, userStationId: string | null) {
    const where: any = {};

    // Station scoping
    if (['STATION_MANAGER'].includes(userRole) && userStationId) {
      where.stationId = userStationId;
    } else if (query.stationId) {
      where.stationId = query.stationId;
    }

    if (query.supplierId) where.supplierId = query.supplierId;
    if (query.status) where.status = query.status;
    if (query.from || query.to) {
      where.orderDate = {};
      if (query.from) where.orderDate.gte = new Date(query.from);
      if (query.to) where.orderDate.lte = new Date(query.to);
    }

    const [items, total] = await Promise.all([
      this.prisma.purchaseOrder.findMany({
        where,
        include: ORDER_INCLUDE,
        orderBy: { createdAt: 'desc' },
        take: Number(query.limit),
        skip: Number(query.offset),
      }),
      this.prisma.purchaseOrder.count({ where }),
    ]);

    return { items: items.map(this.formatOrder), total };
  }

  async getOrder(orderId: string) {
    const order = await this.prisma.purchaseOrder.findUnique({
      where: { id: orderId },
      include: ORDER_INCLUDE,
    });
    if (!order) throw new NotFoundException('Purchase order not found');
    return this.formatOrder(order);
  }

  // ─── Reorder suggestions ──────────────────────────────────────────────────

  async getReorderSuggestions() {
    const allTanks = await this.prisma.tank.findMany({
      include: { station: { select: { id: true, name: true, city: true } } },
    });

    const lowTanks = allTanks.filter(
      (t) => new Decimal(t.currentLevelLitres).lessThanOrEqualTo(t.reorderLevelLitres),
    );

    // For each low tank, check if there's already an open PO
    const suggestions = await Promise.all(
      lowTanks.map(async (tank) => {
        const existingPO = await this.prisma.purchaseOrder.findFirst({
          where: {
            stationId: tank.stationId,
            status: { in: [OrderStatus.DRAFT, OrderStatus.SUBMITTED, OrderStatus.APPROVED] },
            items: { some: { fuelType: tank.fuelType } },
          },
          select: { id: true, orderNumber: true, status: true },
        });

        return {
          tankId: tank.id,
          stationId: tank.stationId,
          stationName: tank.station.name,
          stationCity: tank.station.city,
          fuelType: tank.fuelType,
          currentLevelLitres: Number(tank.currentLevelLitres),
          reorderLevelLitres: Number(tank.reorderLevelLitres),
          reorderQtyLitres: Number(tank.reorderQtyLitres),
          percentageFull: Math.round(
            (Number(tank.currentLevelLitres) / Number(tank.capacityLitres)) * 100,
          ),
          isCritical: new Decimal(tank.currentLevelLitres).lessThanOrEqualTo(
            new Decimal(tank.reorderLevelLitres).times(0.5),
          ),
          existingOpenPO: existingPO,
          needsAction: !existingPO,
        };
      }),
    );

    return suggestions.sort((a, b) => a.currentLevelLitres - b.currentLevelLitres);
  }

  // ─── Summary for dashboard ────────────────────────────────────────────────

  async getOrderSummary(stationId?: string) {
    const where: any = stationId ? { stationId } : {};
    const counts = await this.prisma.purchaseOrder.groupBy({
      by: ['status'],
      where,
      _count: { id: true },
    });

    const summary: Record<string, number> = {};
    for (const row of counts) summary[row.status] = row._count.id;

    const pendingValue = await this.prisma.purchaseOrder.aggregate({
      where: { ...where, status: { in: [OrderStatus.SUBMITTED, OrderStatus.APPROVED] } },
      _sum: { totalAmountLkr: true },
    });

    return {
      draft: summary[OrderStatus.DRAFT] ?? 0,
      submitted: summary[OrderStatus.SUBMITTED] ?? 0,
      approved: summary[OrderStatus.APPROVED] ?? 0,
      delivered: summary[OrderStatus.DELIVERED] ?? 0,
      cancelled: summary[OrderStatus.CANCELLED] ?? 0,
      pendingValueLkr: Number(pendingValue._sum.totalAmountLkr ?? 0),
    };
  }

  // ─── Listen for low-stock events → log reorder suggestion ─────────────────

  @OnEvent('stock.low')
  async handleLowStockAlert(tank: any) {
    this.logger.warn(
      `Reorder suggestion: ${tank.fuelType} at ${tank.station?.name} — ${tank.currentLevelLitres}L`,
    );
    // Future: push reorder suggestion notification via WebSocket
  }

  // ─── Private helpers ──────────────────────────────────────────────────────

  private async getOrderOrThrow(orderId: string) {
    const order = await this.prisma.purchaseOrder.findUnique({
      where: { id: orderId },
      include: ORDER_INCLUDE,
    });
    if (!order) throw new NotFoundException('Purchase order not found');
    return order;
  }

  private assertStatus(order: any, allowed: OrderStatus[], action: string) {
    if (!allowed.includes(order.status)) {
      throw new BadRequestException(
        `Cannot ${action} an order with status ${order.status}. Expected: ${allowed.join(' or ')}`,
      );
    }
  }

  private formatOrder(order: any) {
    const totalReceived = order.grns?.reduce(
      (s: number, g: any) => s + Number(g.totalAmountLkr ?? 0),
      0,
    ) ?? 0;

    const deliveredLitresByFuel: Record<string, number> = {};
    order.grns?.forEach((g: any) => {
      g.items?.forEach((i: any) => {
        deliveredLitresByFuel[i.fuelType] =
          (deliveredLitresByFuel[i.fuelType] ?? 0) + Number(i.receivedQtyLitres);
      });
    });

    return {
      id: order.id,
      orderNumber: order.orderNumber,
      station: order.station,
      supplier: order.supplier,
      status: order.status,
      orderDate: order.orderDate,
      expectedDeliveryDate: order.expectedDeliveryDate,
      deliveredAt: order.deliveredAt,
      totalAmountLkr: Number(order.totalAmountLkr),
      totalReceivedAmountLkr: Number(order.totalReceivedAmountLkr ?? 0),
      notes: order.notes,
      cancellationReason: order.cancellationReason,
      cancelledAt: order.cancelledAt,
      isAutoGenerated: order.isAutoGenerated,
      createdBy: order.createdBy,
      approvedBy: order.approvedBy,
      approvedAt: order.approvedAt,
      items: order.items.map((i: any) => ({
        id: i.id,
        fuelType: i.fuelType,
        quantityLitres: Number(i.quantityLitres),
        pricePerLitreLkr: Number(i.pricePerLitreLkr),
        totalAmountLkr: Number(i.totalAmountLkr),
        deliveredLitres: deliveredLitresByFuel[i.fuelType] ?? 0,
      })),
      grns: order.grns ?? [],
      grnsCount: order.grns?.length ?? 0,
      createdAt: order.createdAt,
      updatedAt: order.updatedAt,
    };
  }

  /** Sri Lanka fiscal year: April–March. April = month 1, March = month 12 */
  private getFiscalPeriod(date: Date) {
    const month = date.getMonth() + 1; // 1-12
    const year = date.getFullYear();
    const fiscalMonth = month >= 4 ? month - 3 : month + 9;
    const fiscalYear = month >= 4 ? year : year - 1;
    return { year: fiscalYear, month: fiscalMonth };
  }

  private async auditLog(userId: string, action: string, entityId: string, details?: string) {
    await this.prisma.auditLog
      .create({
        data: {
          userId,
          action,
          entityType: 'PurchaseOrder',
          entityId,
          newValues: details ? { details } : undefined,
        },
      })
      .catch(() => {});
  }
}
