import { apiClient } from './client';

export interface Supplier {
  id: string;
  name: string;
  registrationNo: string | null;
  vatRegNo: string | null;
  address: string | null;
  contactPerson: string | null;
  contactNumber: string | null;
  email: string | null;
  isActive: boolean;
  isPreferred?: boolean;
}

export interface OrderItem {
  id: string;
  fuelType: string;
  quantityLitres: number;
  pricePerLitreLkr: number;
  totalAmountLkr: number;
  deliveredLitres: number;
}

export interface GRNItem {
  id: string;
  fuelType: string;
  orderedQtyLitres: number;
  receivedQtyLitres: number;
  pricePerLitreLkr: number;
  totalAmountLkr: number;
}

export interface GRN {
  id: string;
  grnNumber: string;
  receivedAt: string;
  totalAmountLkr: number;
  notes: string | null;
  items: GRNItem[];
}

export interface PurchaseOrder {
  id: string;
  orderNumber: string;
  station: { id: string; name: string; city: string };
  supplier: { id: string; name: string; vatRegNo: string | null; contactNumber: string | null };
  status: string;
  orderDate: string;
  expectedDeliveryDate: string | null;
  deliveredAt: string | null;
  totalAmountLkr: number;
  totalReceivedAmountLkr: number;
  notes: string | null;
  cancellationReason: string | null;
  cancelledAt: string | null;
  isAutoGenerated: boolean;
  createdBy: { id: string; fullName: string };
  approvedBy: { id: string; fullName: string } | null;
  approvedAt: string | null;
  items: OrderItem[];
  grns: GRN[];
  grnsCount: number;
  createdAt: string;
}

export interface ReorderSuggestion {
  tankId: string;
  stationId: string;
  stationName: string;
  stationCity: string;
  fuelType: string;
  currentLevelLitres: number;
  reorderLevelLitres: number;
  reorderQtyLitres: number;
  percentageFull: number;
  isCritical: boolean;
  existingOpenPO: { id: string; orderNumber: string; status: string } | null;
  needsAction: boolean;
}

export interface OrderSummary {
  draft: number;
  submitted: number;
  approved: number;
  delivered: number;
  cancelled: number;
  pendingValueLkr: number;
}

export interface CreateOrderPayload {
  stationId: string;
  supplierId: string;
  orderDate: string;
  expectedDeliveryDate?: string;
  items: { fuelType: string; quantityLitres: number; pricePerLitreLkr: number }[];
  notes?: string;
  isAutoGenerated?: boolean;
}

export interface CreateGRNPayload {
  purchaseOrderId: string;
  receivedAt: string;
  items: {
    fuelType: string;
    orderedQtyLitres: number;
    receivedQtyLitres: number;
    pricePerLitreLkr: number;
  }[];
  notes?: string;
}

export const ordersApi = {
  // Stations (lightweight list for selects)
  getStations: async (): Promise<{ id: string; name: string; city: string }[]> => {
    const { data } = await apiClient.get('/stations');
    return data;
  },

  // Suppliers
  getSuppliers: async (stationId?: string): Promise<Supplier[]> => {
    const { data } = await apiClient.get('/orders/suppliers', {
      params: stationId ? { stationId } : undefined,
    });
    return data;
  },

  createSupplier: async (payload: Partial<Supplier>): Promise<Supplier> => {
    const { data } = await apiClient.post('/orders/suppliers', payload);
    return data;
  },

  // Orders
  getOrders: async (params?: {
    stationId?: string; supplierId?: string; status?: string;
    from?: string; to?: string; limit?: number; offset?: number;
  }): Promise<{ items: PurchaseOrder[]; total: number }> => {
    const { data } = await apiClient.get('/orders', { params });
    return data;
  },

  getOrder: async (id: string): Promise<PurchaseOrder> => {
    const { data } = await apiClient.get(`/orders/${id}`);
    return data;
  },

  createOrder: async (payload: CreateOrderPayload): Promise<PurchaseOrder> => {
    const { data } = await apiClient.post('/orders', payload);
    return data;
  },

  submitOrder: async (id: string): Promise<PurchaseOrder> => {
    const { data } = await apiClient.patch(`/orders/${id}/submit`);
    return data;
  },

  approveOrder: async (id: string): Promise<PurchaseOrder> => {
    const { data } = await apiClient.patch(`/orders/${id}/approve`);
    return data;
  },

  cancelOrder: async (id: string, cancellationReason: string): Promise<PurchaseOrder> => {
    const { data } = await apiClient.patch(`/orders/${id}/cancel`, { cancellationReason });
    return data;
  },

  createGRN: async (payload: CreateGRNPayload): Promise<GRN> => {
    const { data } = await apiClient.post('/orders/grn', payload);
    return data;
  },

  getSummary: async (stationId?: string): Promise<OrderSummary> => {
    const { data } = await apiClient.get('/orders/summary', {
      params: stationId ? { stationId } : undefined,
    });
    return data;
  },

  getReorderSuggestions: async (): Promise<ReorderSuggestion[]> => {
    const { data } = await apiClient.get('/orders/reorder-suggestions');
    return data;
  },
};
