import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  ArrayMinSize,
  IsArray,
  IsBoolean,
  IsDateString,
  IsEnum,
  IsNumber,
  IsOptional,
  IsPositive,
  IsString,
  IsUUID,
  MaxLength,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { FuelType } from '@gasstation/shared-types';

export class OrderItemDto {
  @ApiProperty({ enum: FuelType })
  @IsEnum(FuelType)
  fuelType: FuelType;

  @ApiProperty({ example: 20000, description: 'Quantity in litres' })
  @IsNumber({ maxDecimalPlaces: 2 })
  @IsPositive()
  quantityLitres: number;

  @ApiProperty({ example: 340.5, description: 'Price per litre (LKR)' })
  @IsNumber({ maxDecimalPlaces: 4 })
  @IsPositive()
  pricePerLitreLkr: number;
}

export class CreateOrderDto {
  @ApiProperty()
  @IsString()
  stationId: string;

  @ApiProperty()
  @IsString()
  supplierId: string;

  @ApiProperty({ example: '2024-06-20' })
  @IsDateString()
  orderDate: string;

  @ApiPropertyOptional({ example: '2024-06-22' })
  @IsOptional()
  @IsDateString()
  expectedDeliveryDate?: string;

  @ApiProperty({ type: [OrderItemDto] })
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => OrderItemDto)
  items: OrderItemDto[];

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(1000)
  notes?: string;

  @ApiPropertyOptional({ description: 'True if auto-generated by reorder alert' })
  @IsOptional()
  @IsBoolean()
  isAutoGenerated?: boolean;
}
