'use client';

import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { PurchaseOrder, ordersApi } from '@/lib/api/orders.api';
import { OrderStatusBadge } from './OrderStatusBadge';
import { OrderTimeline } from './OrderTimeline';
import { GRNModal } from './GRNModal';
import { cn } from '@/lib/utils';
import { useAuthStore } from '@/store/auth.store';

interface Props {
  order: PurchaseOrder;
  canApprove?: boolean;
}

const FUEL_LABELS: Record<string, string> = {
  PETROL_92: 'Petrol 92', PETROL_95: 'Petrol 95',
  AUTO_DIESEL: 'Auto Diesel', SUPER_DIESEL: 'Super Diesel', KEROSENE: 'Kerosene',
};

function lkr(v: number) {
  return `LKR ${v.toLocaleString('en-LK', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function OrderCard({ order, canApprove }: Props) {
  const [expanded, setExpanded] = useState(false);
  const [showTimeline, setShowTimeline] = useState(false);
  const [showGRN, setShowGRN] = useState(false);
  const [showCancel, setShowCancel] = useState(false);
  const [cancelReason, setCancelReason] = useState('');
  const qc = useQueryClient();
  const user = useAuthStore((s) => s.user);

  const invalidate = () => {
    qc.invalidateQueries({ queryKey: ['orders'] });
    qc.invalidateQueries({ queryKey: ['order-summary'] });
  };

  const submitMutation = useMutation({
    mutationFn: () => ordersApi.submitOrder(order.id),
    onSuccess: invalidate,
  });
  const approveMutation = useMutation({
    mutationFn: () => ordersApi.approveOrder(order.id),
    onSuccess: invalidate,
  });
  const cancelMutation = useMutation({
    mutationFn: () => ordersApi.cancelOrder(order.id, cancelReason),
    onSuccess: () => { invalidate(); setShowCancel(false); },
  });

  const isCancelled = order.status === 'CANCELLED';
  const isDelivered = order.status === 'DELIVERED';
  const canSubmit = order.status === 'DRAFT';
  const canApproveOrder = canApprove && order.status === 'SUBMITTED';
  const canReceive = order.status === 'APPROVED' || order.status === 'PARTIALLY_DELIVERED';
  const canCancel = !['DELIVERED', 'CANCELLED'].includes(order.status);

  return (
    <div className={cn(
      'bg-white rounded-xl border shadow-sm overflow-hidden',
      order.isAutoGenerated && 'border-l-4 border-l-orange-400',
      isCancelled && 'opacity-60',
    )}>
      {/* Header */}
      <div className="px-5 py-4 flex items-start justify-between gap-3">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-mono text-sm font-bold text-gray-900">{order.orderNumber}</span>
            {order.isAutoGenerated && (
              <span className="text-xs bg-orange-100 text-orange-700 px-1.5 py-0.5 rounded font-medium">
                Auto-reorder
              </span>
            )}
            <OrderStatusBadge status={order.status} />
          </div>
          <div className="text-sm text-gray-500 mt-0.5">
            {order.station.name} · {order.supplier.name}
          </div>
          <div className="text-xs text-gray-400 mt-0.5">
            {new Date(order.orderDate).toLocaleDateString('en-LK')}
            {order.expectedDeliveryDate && (
              <> · Expected: {new Date(order.expectedDeliveryDate).toLocaleDateString('en-LK')}</>
            )}
          </div>
        </div>
        <div className="flex flex-col items-end gap-1 shrink-0">
          <span className="text-base font-bold text-gray-900">{lkr(order.totalAmountLkr)}</span>
          {order.totalReceivedAmountLkr > 0 && order.totalReceivedAmountLkr !== order.totalAmountLkr && (
            <span className="text-xs text-emerald-700">
              Received: {lkr(order.totalReceivedAmountLkr)}
            </span>
          )}
          <button
            onClick={() => setExpanded(!expanded)}
            className="text-gray-400 hover:text-gray-600 text-xs underline"
          >
            {expanded ? 'Less' : 'Details'}
          </button>
        </div>
      </div>

      {/* Items summary (collapsed) */}
      {!expanded && (
        <div className="px-5 pb-3 flex gap-2 flex-wrap">
          {order.items.map((item) => (
            <div key={item.id} className="text-xs bg-gray-50 rounded-lg px-3 py-1.5">
              <span className="font-medium">{FUEL_LABELS[item.fuelType] ?? item.fuelType}</span>
              <span className="text-gray-500 ml-1">{item.quantityLitres.toLocaleString()}L</span>
              {item.deliveredLitres > 0 && (
                <span className="text-emerald-600 ml-1">({item.deliveredLitres.toLocaleString()}L rcvd)</span>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Expanded detail */}
      {expanded && (
        <div className="px-5 pb-4 border-t pt-4 space-y-4">
          {/* Items table */}
          <table className="w-full text-sm">
            <thead>
              <tr className="text-xs text-gray-500 uppercase tracking-wide border-b">
                <th className="pb-1.5 text-left">Fuel</th>
                <th className="pb-1.5 text-right">Ordered</th>
                <th className="pb-1.5 text-right">Price/L</th>
                <th className="pb-1.5 text-right">Total</th>
                <th className="pb-1.5 text-right">Received</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {order.items.map((item) => (
                <tr key={item.id}>
                  <td className="py-2">{FUEL_LABELS[item.fuelType] ?? item.fuelType}</td>
                  <td className="py-2 text-right tabular-nums">{item.quantityLitres.toLocaleString()}L</td>
                  <td className="py-2 text-right tabular-nums">LKR {item.pricePerLitreLkr.toFixed(2)}</td>
                  <td className="py-2 text-right tabular-nums font-medium">{lkr(item.totalAmountLkr)}</td>
                  <td className={cn('py-2 text-right tabular-nums', item.deliveredLitres > 0 ? 'text-emerald-700 font-medium' : 'text-gray-400')}>
                    {item.deliveredLitres > 0 ? `${item.deliveredLitres.toLocaleString()}L` : '—'}
                  </td>
                </tr>
              ))}
              <tr className="font-bold text-sm border-t-2">
                <td colSpan={3} className="pt-2">Total</td>
                <td className="pt-2 text-right">{lkr(order.totalAmountLkr)}</td>
                <td />
              </tr>
            </tbody>
          </table>

          {order.notes && (
            <div className="bg-gray-50 rounded-lg px-3 py-2 text-xs text-gray-600">
              <span className="font-medium">Notes: </span>{order.notes}
            </div>
          )}

          {/* GRNs */}
          {order.grns.length > 0 && (
            <div>
              <h4 className="text-xs font-semibold text-gray-600 uppercase tracking-wide mb-2">
                Goods Received Notes
              </h4>
              <div className="space-y-2">
                {order.grns.map((grn) => (
                  <div key={grn.id} className="bg-emerald-50 border border-emerald-200 rounded-lg px-3 py-2">
                    <div className="flex justify-between text-xs">
                      <span className="font-mono font-medium text-emerald-800">{grn.grnNumber}</span>
                      <span className="text-emerald-700 font-semibold">{lkr(grn.totalAmountLkr)}</span>
                    </div>
                    <div className="text-xs text-emerald-600 mt-0.5">
                      {new Date(grn.receivedAt).toLocaleString('en-LK')}
                      {grn.notes && ` · ${grn.notes}`}
                    </div>
                    <div className="flex gap-2 mt-1.5 flex-wrap">
                      {grn.items.map((gi, i) => (
                        <span key={i} className="text-xs bg-white border border-emerald-200 rounded px-2 py-0.5">
                          {FUEL_LABELS[gi.fuelType]}: {gi.receivedQtyLitres.toLocaleString()}L
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Timeline toggle */}
          <button
            onClick={() => setShowTimeline(!showTimeline)}
            className="text-xs text-blue-600 hover:text-blue-800 underline underline-offset-2"
          >
            {showTimeline ? 'Hide timeline' : 'Show order timeline'}
          </button>
          {showTimeline && <OrderTimeline order={order} />}
        </div>
      )}

      {/* Cancel form */}
      {showCancel && (
        <div className="px-5 pb-4 border-t pt-3 space-y-2">
          <label className="block text-xs font-medium text-gray-700">Cancellation reason</label>
          <textarea
            value={cancelReason}
            onChange={(e) => setCancelReason(e.target.value)}
            rows={2}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm resize-none focus:ring-2 focus:ring-red-400"
            placeholder="Reason for cancellation..."
          />
          <div className="flex gap-2">
            <button onClick={() => setShowCancel(false)}
              className="flex-1 py-1.5 border border-gray-300 text-gray-600 rounded-lg text-xs font-medium hover:bg-gray-50">
              Back
            </button>
            <button
              onClick={() => cancelMutation.mutate()}
              disabled={!cancelReason.trim() || cancelMutation.isPending}
              className="flex-1 py-1.5 bg-red-600 text-white rounded-lg text-xs font-semibold disabled:bg-red-300"
            >
              {cancelMutation.isPending ? 'Cancelling…' : 'Confirm Cancel'}
            </button>
          </div>
        </div>
      )}

      {/* Action bar */}
      {!isCancelled && !isDelivered && !showCancel && (
        <div className="px-5 pb-4 flex gap-2 border-t pt-3 flex-wrap">
          {canCancel && (
            <button onClick={() => setShowCancel(true)}
              className="px-3 py-1.5 border border-red-300 text-red-600 rounded-lg text-xs font-medium hover:bg-red-50">
              Cancel
            </button>
          )}
          <div className="flex-1" />
          {canSubmit && (
            <button
              onClick={() => submitMutation.mutate()}
              disabled={submitMutation.isPending}
              className="px-4 py-1.5 bg-blue-600 text-white rounded-lg text-xs font-semibold hover:bg-blue-700 disabled:bg-blue-300"
            >
              {submitMutation.isPending ? 'Submitting…' : 'Submit for Approval →'}
            </button>
          )}
          {canApproveOrder && (
            <button
              onClick={() => approveMutation.mutate()}
              disabled={approveMutation.isPending}
              className="px-4 py-1.5 bg-emerald-600 text-white rounded-lg text-xs font-semibold hover:bg-emerald-700 disabled:bg-emerald-300"
            >
              {approveMutation.isPending ? 'Approving…' : '✓ Approve Order'}
            </button>
          )}
          {canReceive && (
            <button
              onClick={() => setShowGRN(true)}
              className="px-4 py-1.5 bg-orange-500 text-white rounded-lg text-xs font-semibold hover:bg-orange-600"
            >
              + Record Delivery (GRN)
            </button>
          )}
        </div>
      )}

      {showGRN && (
        <GRNModal
          order={order}
          onClose={() => { setShowGRN(false); invalidate(); }}
        />
      )}
    </div>
  );
}
